

INSERT INTO shipment(SHIPMENTID, TRADEID, OP, OPCOUNT, QUANTITY ) VALUES(1, 1, 0, 0, 100);


INSERT INTO shipment(SHIPMENTID, TRADEID, OP, OPCOUNT, QUANTITY ) VALUES(2, 1, 1, 1, 20);

INSERT INTO shipment(SHIPMENTID, TRADEID, OP, OPCOUNT, QUANTITY ) VALUES(3, 1, 1, 1, 30);

INSERT INTO shipment(SHIPMENTID, TRADEID, OP, OPCOUNT, QUANTITY ) VALUES(4, 1, 1, 1, 50);


INSERT INTO shipmentrelation(SHIPMENTID, child ) VALUES(1, 2);
INSERT INTO shipmentrelation(SHIPMENTID, child ) VALUES(1, 3);
INSERT INTO shipmentrelation(SHIPMENTID, child ) VALUES(1, 4);


INSERT INTO shipment(SHIPMENTID, TRADEID, OP, OPCOUNT, QUANTITY ) VALUES(5, 1, 2, 2, 50);

INSERT INTO shipmentrelation(SHIPMENTID, child ) VALUES(2, 5);
INSERT INTO shipmentrelation(SHIPMENTID, child ) VALUES(3, 5);